# Generated by Django 5.2.3 on 2026-08-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_delivery_remove_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='order.order'),
        ),
    ]
